services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./server
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
