version: "3.9"

services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build:
      context: ./server
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
    env_file:
      - ./server/.env
    restart: always

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    env_file:
      - ./client/.env

volumes:
  mongo_data:
