version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./server
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    env_file:
      - ./client/.env

volumes:
  mongo_data:
  client_node_modules:
  server_node_modules:
